import type { Talent } from "@/types/talent";

export const talents: Talent[] = [
  {
    slug: "valentina-duarte",
    name: "Valentina Duarte",
    role: "Actriz",
    category: "actuacion",
    featured: true,
    portraitSeed: 47,
    bio: "Formada en teatro clásico antes de dar el salto a cine y series, Valentina construye personajes desde el gesto contenido antes que desde la palabra. Ha trabajado tanto en producciones independientes como en proyectos de plataforma, siempre priorizando papeles con arco dramático real.",
    vitals: [
      { label: "Idiomas", value: "Español, Inglés" },
      { label: "Especialidades", value: "Drama, Comedia negra" },
    ],
  },
  {
    slug: "mateo-iturbide",
    name: "Mateo Iturbide",
    role: "Modelo",
    category: "modelaje",
    featured: true,
    portraitSeed: 12,
    bio: "Con una presencia editorial reconocible, Mateo se mueve entre campañas de moda y proyectos de imagen de marca sin perder un registro sobrio. Prefiere procesos de casting largos que privilegien coherencia visual sobre volumen de trabajo.",
    vitals: [
      { label: "Altura", value: "1.86 m" },
      { label: "Especialidades", value: "Editorial, Campañas de marca" },
    ],
  },
  {
    slug: "renata-solorzano",
    name: "Renata Solórzano",
    role: "Creadora de Contenido",
    category: "contenido",
    featured: true,
    portraitSeed: 29,
    bio: "Renata construye narrativas de marca de largo aliento en lugar de contenido de consumo inmediato. Su trabajo combina dirección de arte propia con una voz editorial consistente entre plataformas.",
    vitals: [
      { label: "Plataformas", value: "Instagram, YouTube" },
      { label: "Especialidades", value: "Narrativa de marca, Dirección de arte" },
    ],
  },
  {
    slug: "emiliano-vargas",
    name: "Emiliano Vargas",
    role: "Presentador",
    category: "conduccion",
    featured: true,
    portraitSeed: 5,
    bio: "Emiliano conduce con un registro cercano pero preciso, formado en radio antes de pasar a televisión y eventos en vivo. Su fortaleza está en la improvisación controlada y el manejo de entrevistas largas.",
    vitals: [
      { label: "Idiomas", value: "Español, Inglés" },
      { label: "Especialidades", value: "Entrevistas, Eventos en vivo" },
    ],
  },
  {
    slug: "camila-del-bosque",
    name: "Camila del Bosque",
    role: "Actriz",
    category: "actuacion",
    featured: true,
    portraitSeed: 64,
    bio: "Camila alterna entre cine de autor y proyectos comerciales sin perder exigencia técnica. Su formación en danza le da un control físico particular en escenas de acción y coreografía.",
    vitals: [
      { label: "Idiomas", value: "Español, Francés" },
      { label: "Especialidades", value: "Acción, Cine de autor" },
    ],
  },
  {
    slug: "santiago-bracho",
    name: "Santiago Bracho",
    role: "Modelo",
    category: "modelaje",
    featured: true,
    portraitSeed: 33,
    bio: "Santiago trabaja principalmente en catálogo y campañas deportivas, con un enfoque disciplinado en cada proceso de producción. Su trayectoria incluye colaboraciones sostenidas con las mismas marcas por varias temporadas.",
    vitals: [
      { label: "Altura", value: "1.90 m" },
      { label: "Especialidades", value: "Deportivo, Catálogo" },
    ],
  },
  {
    slug: "nicolas-farfan",
    name: "Nicolás Farfán",
    role: "Actor",
    category: "actuacion",
    portraitSeed: 3,
    bio: "Nicolás viene del teatro independiente y aporta un registro más crudo a proyectos de ficción. Está en una etapa de construir trayectoria en cine antes que en televisión masiva.",
    vitals: [
      { label: "Idiomas", value: "Español" },
      { label: "Especialidades", value: "Teatro, Drama social" },
    ],
  },
  {
    slug: "isabela-roldan",
    name: "Isabela Roldán",
    role: "Modelo",
    category: "modelaje",
    portraitSeed: 7,
    bio: "Isabela se especializa en beauty y producto, con una precisión técnica que la hace confiable en sesiones de alto detalle. Combina modelaje con formación en dirección de fotografía.",
    vitals: [
      { label: "Altura", value: "1.72 m" },
      { label: "Especialidades", value: "Beauty, Producto" },
    ],
  },
  {
    slug: "joaquin-meza",
    name: "Joaquín Meza",
    role: "Creador de Contenido",
    category: "contenido",
    portraitSeed: 15,
    bio: "Joaquín produce contenido documental corto para marcas que buscan una narrativa menos publicitaria. Trabaja con equipo propio de edición, lo que le da control sobre el resultado final.",
    vitals: [
      { label: "Plataformas", value: "YouTube, TikTok" },
      { label: "Especialidades", value: "Documental corto" },
    ],
  },
  {
    slug: "fernanda-quiroz",
    name: "Fernanda Quiroz",
    role: "Creadora de Contenido",
    category: "contenido",
    featured: true,
    portraitSeed: 22,
    bio: "Fernanda combina moda y estilo de vida en formatos de plataforma larga, priorizando calidad de producción sobre frecuencia de publicación. Su comunidad la sigue por consistencia, no por viralidad puntual.",
    vitals: [
      { label: "Plataformas", value: "Instagram, YouTube" },
      { label: "Especialidades", value: "Moda, Estilo de vida" },
    ],
  },
  {
    slug: "lucia-bermudez",
    name: "Lucía Bermúdez",
    role: "Conductora",
    category: "conduccion",
    portraitSeed: 36,
    bio: "Lucía conduce contenido cultural y de entretenimiento con un tono editorial poco habitual en el formato. Antes de conducción trabajó como productora, lo que se nota en su manejo de ritmo en cámara.",
    vitals: [
      { label: "Idiomas", value: "Español, Inglés" },
      { label: "Especialidades", value: "Contenido cultural" },
    ],
  },
  {
    slug: "diego-salcedo",
    name: "Diego Salcedo",
    role: "Conductor",
    category: "conduccion",
    portraitSeed: 58,
    bio: "Diego se mueve entre conducción deportiva y cobertura de eventos en vivo, con un estilo directo y poco impostado. Su experiencia incluye transmisiones de larga duración sin pérdida de energía.",
    vitals: [
      { label: "Idiomas", value: "Español" },
      { label: "Especialidades", value: "Cobertura deportiva, Eventos en vivo" },
    ],
  },
];
