import type { Talent } from "@/types/talent";

export const talents: Talent[] = [
  {
    slug: "valentina-duarte",
    name: "Valentina Duarte",
    role: "Actriz",
    category: "actores-actrices",
    featured: true,
    portraitSeed: 47,
    bio: "Formada en circuitos de teatro independiente del Estado de México, Valentina ha dado el salto a cine y series, construyendo personajes desde una mirada cercana a la cultura urbana.",
    vitals: [
      { label: "Idiomas", value: "Español, Inglés" },
      { label: "Especialidades", value: "Drama, Teatro urbano" },
    ],
  },
  {
    slug: "mateo-iturbide",
    name: "Mateo Iturbide",
    role: "Director de Cine y Teatro",
    category: "directores",
    featured: true,
    portraitSeed: 12,
    bio: "Mateo dirige proyectos que cruzan el lenguaje del hip-hop con el teatro y el cine, buscando puestas en escena y narrativas visuales con identidad urbana.",
    vitals: [
      { label: "Formación", value: "Cine y Teatro" },
      { label: "Especialidades", value: "Dirección escénica, Cortometraje" },
    ],
  },
  {
    slug: "renata-solorzano",
    name: "Renata Solórzano",
    role: "Guionista y Dramaturga",
    category: "guionistas",
    featured: true,
    portraitSeed: 29,
    bio: "Renata escribe guiones y obras dramáticas que parten de la cultura hip-hop para hablar de identidad y territorio, con una voz literaria propia.",
    vitals: [
      { label: "Formatos", value: "Teatro, Guion audiovisual" },
      { label: "Especialidades", value: "Dramaturgia urbana" },
    ],
  },
  {
    slug: "emiliano-vargas",
    name: "Emiliano Vargas",
    role: "Rapero",
    category: "cantantes-raperos",
    featured: true,
    portraitSeed: 5,
    bio: "Emiliano combina rap y música urbana con una narrativa autobiográfica, presentándose en foros y festivales del Estado de México.",
    vitals: [
      { label: "Género", value: "Rap, Hip-hop" },
      { label: "Especialidades", value: "Freestyle, Composición" },
    ],
  },
  {
    slug: "camila-del-bosque",
    name: "Camila del Bosque",
    role: "Actriz",
    category: "actores-actrices",
    featured: true,
    portraitSeed: 64,
    bio: "Camila alterna cine independiente y teatro, con formación en danza que aporta un registro físico particular a sus interpretaciones.",
    vitals: [
      { label: "Idiomas", value: "Español" },
      { label: "Especialidades", value: "Teatro físico, Cine independiente" },
    ],
  },
  {
    slug: "santiago-bracho",
    name: "Santiago Bracho",
    role: "Músico",
    category: "musicos",
    featured: true,
    portraitSeed: 33,
    bio: "Santiago es multiinstrumentista y acompaña producciones musicales y presentaciones en vivo, con base en géneros urbanos y tradicionales.",
    vitals: [
      { label: "Instrumento", value: "Guitarra, Percusiones" },
      { label: "Especialidades", value: "Música en vivo" },
    ],
  },
  {
    slug: "nicolas-farfan",
    name: "Nicolás Farfán",
    role: "Actor",
    category: "actores-actrices",
    portraitSeed: 3,
    bio: "Nicolás viene del teatro independiente del Estado de México y construye una trayectoria enfocada en cine y proyectos con raíz social.",
    vitals: [
      { label: "Idiomas", value: "Español" },
      { label: "Especialidades", value: "Teatro, Drama social" },
    ],
  },
  {
    slug: "isabela-roldan",
    name: "Isabela Roldán",
    role: "Productora Musical",
    category: "productores-musicales",
    portraitSeed: 7,
    bio: "Isabela produce y administra repertorios musicales, acompañando a artistas emergentes en la grabación y el catálogo de su obra.",
    vitals: [
      { label: "Especialidades", value: "Producción musical, Gestión de catálogo" },
      { label: "Herramientas", value: "DAW, Mezcla" },
    ],
  },
  {
    slug: "joaquin-meza",
    name: "Joaquín Meza",
    role: "Compositor",
    category: "compositores",
    portraitSeed: 15,
    bio: "Joaquín compone piezas musicales que cruzan el hip-hop con influencias tradicionales mexicanas, colaborando con cantantes y proyectos audiovisuales.",
    vitals: [
      { label: "Géneros", value: "Hip-hop, Música tradicional" },
      { label: "Especialidades", value: "Composición, Arreglos" },
    ],
  },
  {
    slug: "fernanda-quiroz",
    name: "Fernanda Quiroz",
    role: "Cantante",
    category: "cantantes-raperos",
    featured: true,
    portraitSeed: 22,
    bio: "Fernanda es cantante urbana con una propuesta que combina R&B y hip-hop, priorizando calidad de producción sobre volumen de lanzamientos.",
    vitals: [
      { label: "Género", value: "R&B, Hip-hop" },
      { label: "Especialidades", value: "Interpretación vocal" },
    ],
  },
  {
    slug: "lucia-bermudez",
    name: "Lucía Bermúdez",
    role: "Directora de Teatro",
    category: "directores",
    portraitSeed: 36,
    bio: "Lucía dirige puestas en escena que dialogan con la cultura hip-hop y el teatro comunitario del Estado de México.",
    vitals: [
      { label: "Formación", value: "Dirección teatral" },
      { label: "Especialidades", value: "Teatro comunitario" },
    ],
  },
  {
    slug: "diego-salcedo",
    name: "Diego Salcedo",
    role: "Guionista",
    category: "guionistas",
    portraitSeed: 58,
    bio: "Diego escribe guiones para cine y contenidos audiovisuales, con especial interés en historias de artistas emergentes y escena urbana.",
    vitals: [
      { label: "Formatos", value: "Guion de cine, Guion audiovisual" },
      { label: "Especialidades", value: "Narrativa urbana" },
    ],
  },
  {
    slug: "ximena-cordero",
    name: "Ximena Cordero",
    role: "Bailarina",
    category: "bailarines",
    featured: true,
    portraitSeed: 18,
    bio: "Ximena se formó en danza urbana y contemporánea, y hoy encabeza montajes que llevan el hip-hop a escenarios de teatro y festivales del Estado de México.",
    vitals: [
      { label: "Estilos", value: "Hip-hop, Danza contemporánea" },
      { label: "Especialidades", value: "Coreografía, Dirección de cuerpo de baile" },
    ],
  },
  {
    slug: "bruno-alcocer",
    name: "Bruno Alcocer",
    role: "Bailarín",
    category: "bailarines",
    portraitSeed: 41,
    bio: "Bruno viene de la escena de battles urbanos y complementa presentaciones en vivo y producciones audiovisuales con un lenguaje corporal de raíz callejera.",
    vitals: [
      { label: "Estilos", value: "Breaking, Freestyle urbano" },
      { label: "Especialidades", value: "Battles, Performance en vivo" },
    ],
  },
];
